SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[VF$Coach_MemberShip](@X XML)
RETURNS TABLE AS
RETURN (
WITH QXML AS
   (
      SELECT @X.query('//Club_Method').value('(Club_Method/@code)[1]',       'BIGINT') AS CBMT_CODE
   )
SELECT ms.RWNO
      ,CAST(ms.STRT_DATE AS DATE) AS STRT_DATE
      ,CAST(ms.END_DATE AS DATE) AS END_DATE
      ,ms.NUMB_OF_ATTN_MONT
      ,CASE WHEN ms.NUMB_OF_ATTN_MONT > 0 THEN ms.NUMB_OF_ATTN_MONT - ms.SUM_ATTN_MONT_DNRM ELSE 0 END AS SUM_ATTN_MONT_DNRM
      ,dbo.GET_MTOS_U(ms.STRT_DATE) AS PERS_STRT_DATE
      ,dbo.GET_MTOS_U(ms.END_DATE) AS PERS_END_DATE
      ,fp.CBMT_CODE
      ,CAST(cm.STRT_TIME AS VARCHAR(5)) AS STRT_TIME
      ,CAST(cm.END_TIME AS VARCHAR(5)) AS END_TIME
      ,f.FILE_NO
      ,f.NAME_DNRM
      ,f.CELL_PHON_DNRM
      ,f.TELL_PHON_DNRM
      ,f.DEBT_DNRM
      ,f.FNGR_PRNT_DNRM
      ,f.NATL_CODE_DNRM
      ,f.BRTH_DATE_DNRM
      ,dbo.GET_MTOS_U(f.BRTH_DATE_DNRM) AS PERS_BRTH_DATE
      ,DATEDIFF(YEAR, f.BRTH_DATE_DNRM, GETDATE()) AS AGE
      ,m.CODE AS MTOD_CODE
      ,m.MTOD_DESC
      ,cb.CODE AS CTGY_CODE
      ,cb.CTGY_DESC
      ,c.FILE_NO AS COCH_FILE_NO
      ,c.NAME_DNRM AS COCH_NAME_DNRM
  FROM dbo.Member_Ship ms, dbo.Fighter_Public fp, dbo.Fighter f, dbo.Club_Method cm, dbo.Method m, dbo.Category_Belt cb, dbo.Fighter c, QXML Qx
 WHERE ms.FIGH_FILE_NO = fp.FIGH_FILE_NO
   AND ms.RECT_CODE = '004'
   AND ms.FGPB_RWNO_DNRM = fp.RWNO
   AND ms.FGPB_RECT_CODE_DNRM = fp.RECT_CODE
   AND fp.FIGH_FILE_NO = f.FILE_NO
   AND fp.RECT_CODE = '004'
   AND ms.VALD_TYPE = '002'
   AND CAST(GETDATE() AS DATE) BETWEEN CAST(ms.STRT_DATE AS DATE) AND CAST(ms.END_DATE AS DATE)
   AND (ms.NUMB_OF_ATTN_MONT = 0 OR ms.NUMB_OF_ATTN_MONT > ms.SUM_ATTN_MONT_DNRM)
   AND fp.CBMT_CODE = cm.CODE
   AND cm.MTOD_CODE = m.CODE
   AND fp.CTGY_CODE = cb.CODE
   AND c.FILE_NO = cm.COCH_FILE_NO
   
   AND (Qx.CBMT_CODE IS NULL OR (CASE WHEN Qx.CBMT_CODE = 0 THEN cm.CODE ELSE Qx.CBMT_CODE END = cm.CODE))
 )
GO
