SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [dbo].[V$StatisticAttendance]
(	
	@FileNo BIGINT	
)
RETURNS TABLE 
AS
RETURN 
(
	
SELECT SUBSTRING(dbo.GET_MTOS_U(ATTN_DATE), 1, 4) AS YEAR,
       SUBSTRING(dbo.GET_MTOS_U(ATTN_DATE), 6, 2) AS CYCL,
       SUM(CASE WHEN ENTR_TIME BETWEEN '06:00' AND '06:59' THEN 1 END) AS _06_CONT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '06:00' AND '06:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _06_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '06:00' AND '06:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _06_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '07:00' AND '07:59' THEN 1 END) AS _07,
       SUM(CASE WHEN ENTR_TIME BETWEEN '07:00' AND '07:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _07_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '07:00' AND '07:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _07_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '08:00' AND '08:59' THEN 1 END) AS _08,
       SUM(CASE WHEN ENTR_TIME BETWEEN '08:00' AND '08:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _08_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '08:00' AND '08:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _08_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '09:00' AND '09:59' THEN 1 END) AS _09,
       SUM(CASE WHEN ENTR_TIME BETWEEN '09:00' AND '09:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _09_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '09:00' AND '09:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _09_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '10:00' AND '10:59' THEN 1 END) AS _10,
       SUM(CASE WHEN ENTR_TIME BETWEEN '10:00' AND '10:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _10_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '10:00' AND '10:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _10_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '11:00' AND '11:59' THEN 1 END) AS _11,
       SUM(CASE WHEN ENTR_TIME BETWEEN '11:00' AND '11:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _11_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '11:00' AND '11:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _11_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '12:00' AND '12:59' THEN 1 END) AS _12,
       SUM(CASE WHEN ENTR_TIME BETWEEN '12:00' AND '12:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _12_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '12:00' AND '12:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _12_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '13:00' AND '13:59' THEN 1 END) AS _13,
       SUM(CASE WHEN ENTR_TIME BETWEEN '13:00' AND '13:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _13_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '13:00' AND '13:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _13_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '14:00' AND '14:59' THEN 1 END) AS _14,
       SUM(CASE WHEN ENTR_TIME BETWEEN '14:00' AND '14:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _14_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '14:00' AND '14:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _14_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '15:00' AND '15:59' THEN 1 END) AS _15,
       SUM(CASE WHEN ENTR_TIME BETWEEN '15:00' AND '15:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _15_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '15:00' AND '15:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _15_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '16:00' AND '16:59' THEN 1 END) AS _16,
       SUM(CASE WHEN ENTR_TIME BETWEEN '16:00' AND '16:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _16_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '16:00' AND '16:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _16_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '17:00' AND '17:59' THEN 1 END) AS _17,
       SUM(CASE WHEN ENTR_TIME BETWEEN '17:00' AND '17:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _17_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '17:00' AND '17:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _17_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '18:00' AND '18:59' THEN 1 END) AS _18,
       SUM(CASE WHEN ENTR_TIME BETWEEN '18:00' AND '18:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _18_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '18:00' AND '18:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _18_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '19:00' AND '19:59' THEN 1 END) AS _19,
       SUM(CASE WHEN ENTR_TIME BETWEEN '19:00' AND '19:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _19_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '19:00' AND '19:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _19_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '20:00' AND '20:59' THEN 1 END) AS _20,
       SUM(CASE WHEN ENTR_TIME BETWEEN '20:00' AND '20:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _20_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '20:00' AND '20:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _20_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '21:00' AND '21:59' THEN 1 END) AS _21,
       SUM(CASE WHEN ENTR_TIME BETWEEN '21:00' AND '21:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _21_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '21:00' AND '21:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _21_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '22:00' AND '22:59' THEN 1 END) AS _22,
       SUM(CASE WHEN ENTR_TIME BETWEEN '22:00' AND '22:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _22_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '22:00' AND '22:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _22_AVG_MINT,
       SUM(CASE WHEN ENTR_TIME BETWEEN '23:00' AND '23:59' THEN 1 END) AS _23,
       SUM(CASE WHEN ENTR_TIME BETWEEN '23:00' AND '23:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _23_TOTL_MINT,
       AVG(CASE WHEN ENTR_TIME BETWEEN '23:00' AND '23:59' THEN DATEDIFF(MINUTE, ENTR_TIME, EXIT_TIME) END) AS _23_AVG_MINT
  FROM dbo.Attendance
  WHERE (@FileNo IS NULL OR FIGH_FILE_NO = @FileNo)
  GROUP BY SUBSTRING(dbo.GET_MTOS_U(ATTN_DATE), 1, 4),
           SUBSTRING(dbo.GET_MTOS_U(ATTN_DATE), 6, 2)
)
GO
