SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V#User_Localization_Form] AS 
SELECT REGN_LANG, RTL_STAT, FORM_NAME, CNTL_NAME, LABL_TEXT, TOOL_TIP_TEXT, PLAC_HLDR_TEXT, CNTL_TYPE
FROM    iProject.Global.V#User_Localization_Form
WHERE   SUB_SYS = 5;
GO
