SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V$Drat] AS
SELECT CAST(CRET_DATE AS DATE) AS DRAT_DATE, COUNT(CODE) AS DART_NUMB 
  FROM dbo.Dresser_Attendance 
 GROUP BY CAST(CRET_DATE AS DATE);
GO
