SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V#Tables] AS SELECT OBJECT_ID(TABLE_NAME) AS OBJC_ID, TABLE_NAME AS TABL_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE';

GO
