SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V#URQFGA]
AS
SELECT     FGA_CODE, RQTP_CODE, RQTT_CODE, SYS_USER
FROM         dbo.User_Request_Requester_Fgac
WHERE     (REC_STAT = '002') AND (VALD_TYPE = '002')

GO
