SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V$Total_Member_Ship] as
SELECT f.FILE_NO,f.DEBT_DNRM, f.NAME_DNRM, f.CELL_PHON_DNRM, m.MTOD_DESC, cb.CTGY_DESC, 
       ms.RWNO AS MBSP_RWNO, ms.FGPB_COCH_FILE_NO AS COCH_FILE_NO, c.NAME_DNRM AS COCH_NAME_DNRM, c.CELL_PHON_DNRM AS COCH_CELL_PHON_DNRM, ms.STRT_DATE, ms.END_DATE, ms.FGPB_CBMT_CODE_DNRM AS CBMT_CODE
  FROM dbo.V#Member_Ship ms, dbo.Fighter f, dbo.Method m, dbo.Category_Belt cb, dbo.Fighter c
 WHERE ms.FIGH_FILE_NO = f.FILE_NO
   AND ms.FGPB_MTOD_CODE_DNRM = m.CODE
   AND ms.FGPB_CTGY_CODE_DNRM = cb.CODE
   AND ms.FGPB_COCH_FILE_NO = c.FILE_NO;
   --AND CAST(GETDATE() AS DATE) BETWEEN CAST(ms.STRT_DATE AS DATE) AND CAST(ms.END_DATE AS DATE);
GO
