SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V#Events] AS
SELECT f.FILE_NO, f.SEX_TYPE_DNRM, f.CELL_PHON_DNRM, f.CHAT_ID_DNRM, f.NAME_DNRM, f.BRTH_DATE_DNRM AS EVNT_DATE, N'001' AS EVNT_TYPE, N'تولدت مبارک' AS EVNT_DESC
  FROM dbo.Fighter f
 WHERE f.CONF_STAT = '002'
   AND f.BRTH_DATE_DNRM != CAST(f.CONF_DATE AS DATE)
   AND f.BRTH_DATE_DNRM >= CAST(GETDATE() AS DATE)

UNION ALL

SELECT f.FILE_NO, f.SEX_TYPE_DNRM, f.CELL_PHON_DNRM, f.CHAT_ID_DNRM, f.NAME_DNRM, f.INSR_DATE_DNRM, N'002', N'اعتبار بیمه'
  FROM dbo.Fighter f
 WHERE f.CONF_STAT = '002'
   AND f.INSR_DATE_DNRM >= CAST(GETDATE() AS DATE)

UNION ALL

SELECT f.FILE_NO, f.SEX_TYPE_DNRM, f.CELL_PHON_DNRM, f.CHAT_ID_DNRM, f.NAME_DNRM, ms.END_DATE, '003', m.MTOD_DESC + N' - ' + cb.CTGY_DESC
  FROM dbo.Fighter f, dbo.Member_Ship ms, dbo.Method m, dbo.Category_Belt cb
 WHERE f.FILE_NO = ms.FIGH_FILE_NO
   AND ms.FGPB_MTOD_CODE_DNRM = m.CODE
   AND ms.FGPB_CTGY_CODE_DNRM = cb.CODE
   AND ms.RECT_CODE = '004'
   AND ms.VALD_TYPE = '002'
   AND ( (ms.NUMB_OF_ATTN_MONT = 0 AND CAST(ms.END_DATE AS DATE) >= CAST(GETDATE() AS DATE)) 
         OR 
         (ms.NUMB_OF_ATTN_MONT != 0 AND CAST(ms.END_DATE AS DATE) >= CAST(GETDATE() AS DATE) AND ms.NUMB_OF_ATTN_MONT > ms.SUM_ATTN_MONT_DNRM) )

UNION ALL
         
SELECT f.FILE_NO, f.SEX_TYPE_DNRM, f.CELL_PHON_DNRM, f.CHAT_ID_DNRM, f.NAME_DNRM, pd.EXPR_DATE, '004', pd.PYDT_DESC
  FROM dbo.Fighter f, dbo.Request r, dbo.Request_Row rr, dbo.Payment_Detail pd
 WHERE r.RQID = rr.RQST_RQID
   AND rr.FIGH_FILE_NO = f.FILE_NO
   AND rr.RQST_RQID = pd.PYMT_RQST_RQID
   AND r.RQST_STAT = '002'
   AND CAST(pd.EXPR_DATE AS DATE) != CAST(r.SAVE_DATE AS DATE)
   AND CAST(pd.EXPR_DATE AS DATE) >= CAST(GETDATE() AS DATE)

UNION ALL

SELECT f.FILE_NO, f.SEX_TYPE_DNRM, f.CELL_PHON_DNRM, f.CHAT_ID_DNRM, f.NAME_DNRM, pc.CHEK_DATE, '005', pc.CHEK_OWNR + N' - ' + pc.CHEK_NO + N' - ' + pc.BANK
  FROM dbo.Payment_Check pc, dbo.Request_Row rr, dbo.Fighter f
 WHERE pc.RQRO_RQST_RQID = rr.RQST_RQID
   AND pc.RQRO_RWNO = rr.RWNO
   AND rr.FIGH_FILE_NO = f.FILE_NO
   AND pc.CHEK_DATE >= CAST(GETDATE() AS DATE)
   AND ISNULL(pc.CHEK_TYPE, '000') IN ('000', '001')
GO
