SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V#UCFGA]
AS
SELECT     FGA_CODE, CLUB_CODE, SYS_USER, MAST_SYS_USER
FROM         dbo.User_Club_Fgac
WHERE     (REC_STAT = '002') AND (VALD_TYPE = '002')

GO
