SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V#Users]
AS
SELECT     UPPER(USERDB) AS USER_DB, ID, ShortCut, TitleFa AS USER_NAME, AMIL_ADRS, MAIL_SRVR, EMAL_ADRS, EMAL_PASS, CELL_PHON, TELL_PHON, VOIP_NUMB, MAIL_SRVR_STAT, 
                      MAIL_SRVR_PROF, MAIL_SRVR_ACNT, DFLT_USER_HELP_SRVR, REGN_PRVN_CNTY_CODE, REGN_PRVN_CODE, REGN_CODE
FROM         iProject.DataGuard.[User] AS a
WHERE     (LEN(USERDB) > 0) AND (USERDB <> 'scott')

GO
DECLARE @xp int
SELECT @xp=1

GO
