SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V#GainLoss] AS
SELECT  f.SEX_TYPE_DNRM,
        dbo.GET_MTOS_U(g.PAID_DATE) AS ACTN_DATE,
        SUBSTRING(dbo.GET_MTOS_U(g.PAID_DATE), 1, 4) AS YEAR,
        SUBSTRING(dbo.GET_MTOS_U(g.PAID_DATE), 6, 2) AS CYCL,
        g.DPST_STAT,
        COUNT(g.GLID) AS CONT,
        SUM(CASE gd.RCPT_MTOD WHEN '003' THEN (CASE g.DPST_STAT WHEN '002' THEN gd.AMNT WHEN '001' THEN -gd.AMNT END) ELSE 0 END) AS POS_AMNT,
        SUM(CASE WHEN gd.RCPT_MTOD != '003' THEN (CASE g.DPST_STAT WHEN '002' THEN gd.AMNT WHEN '001' THEN -gd.AMNT END) ELSE 0 END) AS CASH_AMNT
FROM    dbo.Gain_Loss_Rial g ,
        dbo.Gain_Loss_Rail_Detail gd,
        dbo.Fighter f
WHERE g.GLID = gd.GLRL_GLID
  AND g.FIGH_FILE_NO = f.FILE_NO
  AND g.CONF_STAT = '002'
  GROUP BY f.SEX_TYPE_DNRM,
        dbo.GET_MTOS_U(g.PAID_DATE),
        SUBSTRING(dbo.GET_MTOS_U(g.PAID_DATE), 1, 4),
        SUBSTRING(dbo.GET_MTOS_U(g.PAID_DATE), 6, 2),
        g.DPST_STAT;
  

GO
