SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE VIEW [dbo].[V#Computers] AS
SELECT a.IP_DNRM, a.CPU_SRNO_DNRM, a.COMP_NAME_DNRM, a.NAME_DNRM  FROM iProject.DataGuard.[Gateway] a ;


GO
