SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[UPD_COMM_P](
   @RQST_RQID BIGINT
  ,@COMM_TYPE VARCHAR(3)
  ,@Cmid      BIGINT OUT
)
AS
BEGIN
   UPDATE Committee
      SET COMM_TYPE = @COMM_TYPE
    WHERE RQST_RQID = @RQST_RQID
      AND CMID = @Cmid;
END;
GO
