SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[UPD_ACDT_P] 
   @ACTN_REGN_PRVN_CNTY_CODE VARCHAR(3)
  ,@ACTN_REGN_PRVN_CODE VARCHAR(3)
  ,@ACTN_REGN_CODE VARCHAR(3)
  ,@ACTN_CLUB_CODE BIGINT
  ,@ACTN_RWNO BIGINT
  ,@AMNT BIGINT
  ,@AMNT_TYPE VARCHAR(3)
  ,@AMNT_DATE DATE
  ,@PYMT_CASH_CODE BIGINT
  ,@PYMT_RQST_RQID BIGINT
  ,@MSEX_CODE BIGINT
  ,@RWNO INT OUT
AS
BEGIN
   UPDATE Account_Detail
      SET [AMNT] = @AMNT         
    WHERE [ACTN_REGN_PRVN_CNTY_CODE] = @ACTN_REGN_PRVN_CNTY_CODE
      AND [ACTN_REGN_PRVN_CODE] = @ACTN_REGN_PRVN_CODE
      AND [ACTN_REGN_CODE] = @ACTN_REGN_CODE
      AND [ACTN_CLUB_CODE] = @ACTN_CLUB_CODE
      AND [ACTN_RWNO] = @ACTN_RWNO
      AND [AMNT_TYPE] = @AMNT_TYPE
      AND [AMNT_DATE] = @AMNT_DATE
      AND [RWNO] = @RWNO;
END;
GO
