SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[UPD_ACTN_P] 
   @REGN_PRVN_CNTY_CODE VARCHAR(3)
  ,@REGN_PRVN_CODE VARCHAR(3)
  ,@REGN_CODE VARCHAR(3)
  ,@CLUB_CODE BIGINT
  ,@SUM_AMNT BIGINT
  ,@AMNT_TYPE VARCHAR(3)
  ,@AMNT_DATE DATETIME
  ,@RWNO BIGINT
AS
BEGIN
   UPDATE Account
      SET [SUM_AMNT] += @SUM_AMNT         
    WHERE [REGN_PRVN_CNTY_CODE] = @REGN_PRVN_CNTY_CODE
      AND [REGN_PRVN_CODE] = @REGN_PRVN_CODE
      AND [REGN_CODE] = @REGN_CODE
      AND [CLUB_CODE] = @CLUB_CODE
      AND [AMNT_TYPE] = @AMNT_TYPE
      AND [AMNT_DATE] = @AMNT_DATE
      AND [RWNO] = @RWNO;
END;
GO
