CREATE TABLE [dbo].[Survey]
(
[CALL_CODE] [bigint] NULL,
[CODE] [bigint] NOT NULL,
[SURV_APBS_CODE] [bigint] NULL,
[SURV_CMNT] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SURV_RTNG_NUMB] [int] NULL,
[CRET_BY] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRET_DATE] [datetime] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[CG$AINS_SURV] ON [dbo].[Survey]
AFTER INSERT
AS
BEGIN
   MERGE dbo.Survey T
   USING (SELECT * FROM Inserted) S
   ON (T.Call_Code = S.Call_Code AND
       T.Code = S.Code)
   WHEN MATCHED THEN
      UPDATE SET
         T.CRET_BY = UPPER(SUSER_NAME()),
         T.CRET_DATE = GETDATE(),
         T.CODE = CASE S.CODE WHEN 0 THEN dbo.GNRT_NVID_U() ELSE S.CODE END;
END;
GO
ALTER TABLE [dbo].[Survey] ADD CONSTRAINT [PK_SURV] PRIMARY KEY CLUSTERED  ([CODE]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Survey] ADD CONSTRAINT [FK_SURV_APBS] FOREIGN KEY ([SURV_APBS_CODE]) REFERENCES [dbo].[App_Base_Define] ([CODE])
GO
ALTER TABLE [dbo].[Survey] ADD CONSTRAINT [FK_SURV_CALL] FOREIGN KEY ([CALL_CODE]) REFERENCES [dbo].[Fighter_Call] ([CODE]) ON DELETE CASCADE
GO
