CREATE TABLE [dbo].[Advertising_Campaign]
(
[ADVP_CODE] [bigint] NULL,
[CODE] [bigint] NOT NULL,
[CELL_PHON] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRET_BY] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRET_DATE] [datetime] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[CG$AINS_ADVC] ON [dbo].[Advertising_Campaign]
AFTER INSERT
AS
BEGIN
   MERGE Advertising_Campaign T
   USING (SELECT * FROM INSERTED) S
   ON (T.ADVP_CODE = S.ADVP_CODE AND
       T.CODE = S.CODE)
   WHEN MATCHED THEN
      UPDATE SET 
         T.CRET_BY = UPPER(SUSER_NAME()),
         T.CRET_DATE = GETDATE(),
         T.CODE = CASE S.CODE WHEN 0 THEN dbo.GNRT_NVID_U() ELSE S.CODE END;
END
GO
ALTER TABLE [dbo].[Advertising_Campaign] ADD CONSTRAINT [PK_ADVC] PRIMARY KEY CLUSTERED  ([CODE]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Advertising_Campaign] ADD CONSTRAINT [FK_ADVC_ADVP] FOREIGN KEY ([ADVP_CODE]) REFERENCES [dbo].[Advertising_Parameter] ([CODE]) ON DELETE CASCADE
GO
