CREATE TABLE [dbo].[Fighter_RelationShip]
(
[FIGH_FILE_NO] [bigint] NULL,
[FGRS_FIGH_FILE_NO] [bigint] NULL,
[CODE] [int] NOT NULL,
[RLTS_CODE] [bigint] NULL,
[RLTS_DESC] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRET_BY] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRET_DATE] [datetime] NULL,
[MDFY_BY] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDFY_DATE] [datetime] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[CG$AINS_FGRS] ON [dbo].[Fighter_RelationShip]
AFTER INSERT
AS
BEGIN
   MERGE Fighter_RelationShip T
   USING (SELECT * FROM INSERTED) S
   ON (T.FIGH_FILE_NO = S.FIGH_FILE_NO AND 
       T.FGRS_FIGH_FILE_NO = S.FGRS_FIGH_FILE_NO AND 
       T.CODE = S.CODE)
   WHEN MATCHED THEN 
      UPDATE SET 
         T.CRET_BY = UPPER(SUSER_NAME()),
         T.CRET_DATE = GETDATE(),
         T.CODE = CASE S.CODE WHEN 0 THEN dbo.GNRT_NVID_U() ELSE S.CODE END;
END;
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[CG$AUPD_FGRS] ON [dbo].[Fighter_RelationShip]
WITH EXEC AS CALLER
AFTER UPDATE
AS
BEGIN
   MERGE Fighter_RelationShip T
   USING (SELECT * FROM INSERTED) S
   ON (T.CODE = S.CODE)
   WHEN MATCHED THEN 
      UPDATE SET 
         T.MDFY_BY = UPPER(SUSER_NAME()),
         T.MDFY_DATE = GETDATE();
END;
GO
ALTER TABLE [dbo].[Fighter_RelationShip] ADD CONSTRAINT [PK_FGRS] PRIMARY KEY CLUSTERED  ([CODE]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Fighter_RelationShip] ADD CONSTRAINT [FK_FGRS_APBS] FOREIGN KEY ([RLTS_CODE]) REFERENCES [dbo].[App_Base_Define] ([CODE]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Fighter_RelationShip] ADD CONSTRAINT [FK_FGRS_FIGH_C] FOREIGN KEY ([FGRS_FIGH_FILE_NO]) REFERENCES [dbo].[Fighter] ([FILE_NO])
GO
ALTER TABLE [dbo].[Fighter_RelationShip] ADD CONSTRAINT [FK_FGRS_FIGH_R] FOREIGN KEY ([FIGH_FILE_NO]) REFERENCES [dbo].[Fighter] ([FILE_NO]) ON DELETE CASCADE
GO
