CREATE TABLE [dbo].[Advertising_Campaign]
(
[ADVP_CODE] [bigint] NULL,
[CODE] [bigint] NOT NULL,
[CELL_PHON] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIGH_FILE_NO] [bigint] NULL,
[RECD_STAT] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RQST_RQID] [bigint] NULL,
[ACTN_DATE] [datetime] NULL,
[CRET_BY] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRET_DATE] [datetime] NULL,
[MDFY_BY] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDFY_DATE] [datetime] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[CG$AINS_ADVC] ON [dbo].[Advertising_Campaign]
AFTER INSERT
AS
BEGIN
   MERGE Advertising_Campaign T
   USING (SELECT * FROM INSERTED) S
   ON (T.ADVP_CODE = S.ADVP_CODE AND
       T.CODE = S.CODE)
   WHEN MATCHED THEN
      UPDATE SET 
         T.CRET_BY = UPPER(SUSER_NAME()),
         T.CRET_DATE = GETDATE(),         
         T.CODE = CASE S.CODE WHEN 0 THEN dbo.GNRT_NVID_U() ELSE S.CODE END,
         T.RECD_STAT = ISNULL(s.RECD_STAT, '002');
END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[CG$AUPD_ADVC] ON [dbo].[Advertising_Campaign]
AFTER UPDATE
AS
BEGIN
   MERGE Advertising_Campaign T
   USING (SELECT * FROM INSERTED) S
   ON (T.CODE = S.CODE)
   WHEN MATCHED THEN
      UPDATE SET 
         T.MDFY_BY = UPPER(SUSER_NAME()),
         T.MDFY_DATE = GETDATE();
         
END
GO
ALTER TABLE [dbo].[Advertising_Campaign] ADD CONSTRAINT [PK_ADVC] PRIMARY KEY CLUSTERED  ([CODE]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Advertising_Campaign] ADD CONSTRAINT [FK_ADVC_ADVP] FOREIGN KEY ([ADVP_CODE]) REFERENCES [dbo].[Advertising_Parameter] ([CODE]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Advertising_Campaign] ADD CONSTRAINT [FK_ADVC_FIGH] FOREIGN KEY ([FIGH_FILE_NO]) REFERENCES [dbo].[Fighter] ([FILE_NO]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Advertising_Campaign] ADD CONSTRAINT [FK_ADVC_RQST] FOREIGN KEY ([RQST_RQID]) REFERENCES [dbo].[Request] ([RQID]) ON DELETE SET NULL
GO
