CREATE TABLE [dbo].[Fighter_Call]
(
[FIGH_FILE_NO] [bigint] NULL,
[CODE] [bigint] NOT NULL,
[CALL_DESC] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CALL_CMNT] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CALL_DATE] [datetime] NULL,
[RSLT_APBS_CODE] [bigint] NULL,
[CRET_BY] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRET_DATE] [datetime] NULL,
[MDFY_BY] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDFY_DATE] [datetime] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[CG$AINS_CALL] ON [dbo].[Fighter_Call]
FOR INSERT
AS
BEGIN
   MERGE dbo.Fighter_Call T
   USING (SELECT * FROM Inserted) S
   ON (T.FIGH_FILE_NO = S.FIGH_FILE_NO AND 
       T.CODE = S.CODE)
   WHEN MATCHED THEN
      UPDATE SET
      T.CRET_BY = UPPER(SUSER_NAME()),
      T.CRET_DATE = GETDATE(),
      T.CODE = CASE S.CODE WHEN 0 THEN dbo.GNRT_NVID_U() ELSE S.CODE END;
END;
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[CG$AUPD_CALL] ON [dbo].[Fighter_Call]
AFTER UPDATE
AS
BEGIN
   MERGE dbo.Fighter_Call T
   USING(SELECT * FROM Inserted) S
   ON (T.Code = S.Code)
   WHEN MATCHED THEN
      UPDATE SET
         T.MDFY_BY = UPPER(SUSER_NAME()),
         T.MDFY_DATE = GETDATE();
END;
GO
ALTER TABLE [dbo].[Fighter_Call] ADD CONSTRAINT [PK_CALL] PRIMARY KEY CLUSTERED  ([CODE]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Fighter_Call] ADD CONSTRAINT [FK_CALL_APBS] FOREIGN KEY ([RSLT_APBS_CODE]) REFERENCES [dbo].[App_Base_Define] ([CODE]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Fighter_Call] ADD CONSTRAINT [FK_CALL_FIGH] FOREIGN KEY ([FIGH_FILE_NO]) REFERENCES [dbo].[Fighter] ([FILE_NO]) ON DELETE CASCADE
GO
